
spring:
  application:
    name: service-java8-b
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://eureka:8080/eureka/}
  instance:
    prefer-ip-address: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
